### PR TITLE
add py312 support

### PR DESCRIPTION
**Pull request by vppuzakov**
- remove legacy python support
- pin cython, pydantic, flask, aiohttp versions
- disable debug mode in coveralls
- fix mypy typing test

### CODE REVIEW

**Comment by colonelpanic8** [comment]
@vppuzakov if this doesnt get merged soon, i feel like we should consider forking so that we can maintain this somewhere.

@rmk135 do you have any intention to continue maintaining? if not you should really consider maybe handing over control to the community.

**Comment by vppuzakov** [comment]
@colonelpanic8, already create [organization](https://github.com/python-dependency-injector) and fork [repo](https://github.com/python-dependency-injector/python-dependency-injector)

merged version published as [dependency-injector2](https://pypi.org/project/dependency-injector2/)

**Comment by colonelpanic8** [comment]
@vppuzakov cool, but the repo doesn't actually have this changed merged in afaict

**Comment by EnotShow** [comment]
Awesome work! It is so strange that it didn't merged yet

**Comment by ZipFile** [comment]
Thanks for contribution! Unfortunately, I have to close this this PR in favor of #832, #813, #829 and #828.

**Pull request closed without merging**
