### PR TITLE
Added SingletonPerThread provider

### PR DESCRIPTION
**Pull request by sirkonst**
Very useful for me :-)

### CODE REVIEW

**Comment by rmk135** [comment]
Hello,

Just wanted to say "Thanks". I will take a look a bit latter.

Roman

**Comment by rmk135** [comment]
Hello Konstantin,

I've reworked a bit your idea and merged it in terms of PR #132. Also I've added a special section in documentation about using singletons in multi-threading applications.

I productized new version with number 2.1.0 (http://python-dependency-injector.ets-labs.org/en/stable/main/changelog.html) and it's been available on PyPi (https://pypi.python.org/pypi/dependency_injector/2.1.0), so you're welcome to upgrade.

PS: Thanks a lot for your contribution, I have added you in a list of contributors (https://github.com/ets-labs/python-dependency-injector/blob/master/CONTRIBUTORS.rst). Hope you are fine with that ;)

Thanks,
Roman

**Comment by sirkonst** [comment]
Thanks! Great library!

**Comment by rmk135** [comment]
Thank you 😊

**Pull request closed without merging**
