### PR TITLE
Normalize package names by PEP-503

### PR DESCRIPTION
**Pull request by sirkonst**
See https://www.python.org/dev/peps/pep-0503/

### CODE REVIEW

**Comment by rmk135** [comment]
Hello Konstantin,

Thanks for this, once more :) I will take a detail look and merge it a bit later, cause I really want to check that everything (links, CI, etc...) would work as expected.

Thanks,
Roman

**Comment by rmk135** [comment]
Thanks :)

**Comment by rmk135** [comment]
Change has been productized in version 2.1.1 - available on PyPI https://pypi.python.org/pypi/dependency_injector

**Comment by sirkonst** [comment]
Great!

**Pull request merged**
