### PR TITLE
regenerate .c files

### PR DESCRIPTION
**Pull request by hp-peti**
using Cython 0.29.37

this enables compilation with cpython 3.12 header

nothing else was changed

### CODE REVIEW

**Comment by hp-peti** [comment]
- pyproject.toml-based installations work
- usage with betterproto and grpclib was successful 
- not tested with python <3.12 though

**Comment by hp-peti** [comment]
might fix #787

**Comment by hp-peti** [comment]
might fix #771 as well

**Comment by ZipFile** [comment]
We no longer store generated C files in the source tree, so this PR is no longer relevant. Latest release should be compatible with recent Python versions either way, so clothing.

**Pull request closed without merging**
