### PR TITLE
Add Python 3.12 Support (#752)

### PR DESCRIPTION
**Pull request by rmk135**
* Ignore .vscode

* Python 3.12 Support

* Change base python to 3.12 and pin pydantic to V1

* all tests passed

* ci: change default python to 3.12

* remove legacy python versions

* annotate pydantic models for tests

### CODE REVIEW

**Comment by macieyng** [comment]
👋 Can you estimate when this PR will be finished?

**Comment by anton-petrov** [comment]
@rmk135 please, can you give us (community) some expectations about this pr?

**Comment by anton-petrov** [comment]
Maybe temporarily merge PR despite of some failed unit tests...

**Comment by macieyng** [comment]
@boonya @ustims, you guys seem to be working for ets-labs. Can you contact @rmk135?

**Comment by MahmudulHassan5809** [comment]
hello @rmk135 , is there any update about this PR.

**Comment by Pentusha** [comment]
@anton-petrov 
I would be very grateful if you could publish compiled wheels to PyPI.

**Comment by MahmudulHassan5809** [comment]
> @anton-petrov 
> I would be very grateful if you could publish compiled wheels to PyPI.

Yeah plz do it if possible. Will help me a lot

**Comment by JacobGeoGeek** [comment]
@rmk135 any update on this PR?

**Comment by MahmudulHassan5809** [comment]
@rmk135  please give a reply. I need to upgrade our project to python 3.12 . it is now mandatory for use .but due to this package can not upgrade .  and it will be difficult for us to use others alternative packages cause in that case need to change lot of things . Please give some update . 
Thanks

**Comment by s-maheshbabu** [comment]
@rmk135  has no Github activity over the last two months. They are probably not just ignoring the requests here but are unable to check Github for whatever reasons. 

@StummeJ as a previous contributor of this repo, are you able to help merging this PR? Or advice on who might be able to help?
(sorry for the random ping.. just chose the last person to contribute to this repo that is not @rmk135)

**Comment by macieyng** [comment]
If any of you have LinkedIn Premium than you can go ahead and ping @rmk135 there. Here is a link to his [profile](https://www.linkedin.com/in/roman-mogylatov-35a21854/). All I could do was to left a [comment]( https://www.linkedin.com/feed/update/urn:li:ugcPost:7156314115689385984?commentUrn=urn%3Ali%3Acomment%3A%28ugcPost%3A7156314115689385984%2C7156413313122275328%29&replyUrn=urn%3Ali%3Acomment%3A%28ugcPost%3A7156314115689385984%2C7157659543991136256%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287156413313122275328%2Curn%3Ali%3AugcPost%3A7156314115689385984%29&dashReplyUrn=urn%3Ali%3Afsd_comment%3A%287157659543991136256%2Curn%3Ali%3AugcPost%3A7156314115689385984%29).

**Comment by Pentusha** [comment]
First, python 3.12 support was initiated by @rmk135 and then he disappeared. Then @anton-petrov started developing of his fork and disappeared too. Well, now it's my time to take that risk. 

I took Anton's PR and made some improvements to the point where it become possible to build and [publish](https://pypi.org/project/dependency-injector-fork/) to PyPI. I didn't bother figuring out how to build packages for old interpreters and dropped [this](https://github.com/ets-labs/python-dependency-injector/blob/master/.github/workflows/tests-and-linters.yml#L7-L21) code.
I'm not sure I have time to maintain the library either, so I can't promise I'll be merging any other PRs, but I can try.

**Comment by gokturkDev** [comment]
this is sad :/ I guess this is end for this library in production environments.

**Comment by PunRabbit** [comment]
Oh, is it really no more update...? 😢

**Comment by lesnik512** [comment]
Hello, for my job I wrote small DI framework as a replacement for dependency-injector with minimal changes https://github.com/modern-python/that-depends

No wiring and Python 3.12 is supported.

**Comment by camcima** [comment]
Does anyone have any idea why coveralls is showing 0% coverage? @macieyng @zeshuaro @MahmudulHassan5809 @anton-petrov

**Comment by rmk135** [comment]
@camcima Because the version of Cython in this PR can't compile the C code with the needed instructions for calculating coverage. The newest version of Cython runs into a segmentation fault error on every other test. There is not good solution to fix coverage now.

**Comment by macieyng** [comment]
any other tool can be used instead of coveralls? if not then is this package development blocked for py3.12 until coveralls resolve their issues?

**Comment by Jamim** [comment]
> any other tool can be used instead of coveralls? if not then is this package development blocked for py3.12 until coveralls resolve their issues?

[Codecov](https://about.codecov.io) might be a great choice.
You can find other alternatives [here](https://www.slant.co/topics/2188/~best-code-coverage-services).

**Comment by biyani701** [comment]
Any update on this? If this library is no longer maintained, what are the alternative options?

**Comment by graham-atom** [comment]
any news on when this will be released? this is blocking us from migrating to python 3.12

**Comment by MahmudulHassan5809** [comment]
@rmk135  please give us some updates.

**Comment by zjpiazza** [comment]
Its a damn shame. I absolutely love this library and it is so useful for building well designed Python applications. Hopefully we get a resolution on the  ownership of the repository. But also, everyone should chill out on harassing people to get what you want. That is always the danger of using open-source libraries in production.

**Comment by osminogin** [comment]
Nobody owes you anything. It’s not clear where the complaints come from, if you don’t buy commercial support, you don’t pay for the developer’s time. A person may have his own priorities, problems, including health or personal ones. Solve the issue of owning the repositories of your projects, and not those of others.

I really hope that Roman will return to active development, but in the current situation I just spent 30 minutes of time and put together my own version for my projects, including several patches, including support for 3.12, no problems with that either.

**Comment by biyani701** [comment]
@osminogin 
if you are able to compile this library with Python 3.12, will you be able to share steps as to how you accomplished it?

**Comment by osminogin** [comment]
@biyani701 The way I recommend is to fork this project and cherry-pick needed commits from @anton-petrov and @Pentusha forks. Repositories and a list of commits that may interest you can be found here https://github.com/ets-labs/python-dependency-injector/compare/master...osminogin:python-dependency-injector:master As an option (I don’t recommend it), you can take my fork, which already has these changes applied. 

Next you need a compiler, required libraries and headers, as usual, building wheel is done with the command `python setup.py bdist_wheel`

Don't forget to add some kind of suffix to your version or increment the version in `src/dependency_injector/__init__.py` to avoid conflicts with the existing original version.

As far as I understand, this patch allows this project to be built with Python 3.12 and old version of Cython ABI. Supporting Python 3.12 with the new Cython ABI version requires some big changes, and apparently some of the difficulties are caused by this.

**Comment by rmk135** [comment]
Hi all!

I'm planning to release this version as a beta release`4.42.0b`. The version of Cython that this release is built on seems to be deficient. The tests are passing, but the coverage calculation doesn't work. Since there were a lot of C API changes in Python 3.12 I think it'd be fair to assume that there are potentially more degraded parts. Releasing this branch as a beta version will prevent automatic updates for people who didn't pin their current versions.

**Comment by rmk135** [comment]
The release with Python 3.12 support is on PyPI: https://pypi.org/project/dependency-injector/4.42.0b1/

```
pip install dependency-injector==4.42.0b1
```

Please report any issues you notice by opening an issue here: https://github.com/ets-labs/python-dependency-injector/issues

I'll publish the plan for future steps a bit later. There is a lot of work to do.

**Comment by rmk135** [comment]
Hi all!

Here's the roadmap for 2024: https://github.com/ets-labs/python-dependency-injector/issues/812

**Pull request merged**
