### PR TITLE
Fix flask ext deprecation warning message

### PR DESCRIPTION
**Pull request by kootoopas**

### CODE REVIEW

**Review by rmk135 — APPROVED** [review]

**Comment by rmk135** [comment]
Hey @kootoopas , thanks for the fix. Can you, please, re-target the pull request to the `develop` brach? Branch `master` is used only for the latest stable release is published to PyPI.

**Comment by rmk135** [comment]
@kootoopas , thank you, merging.

**Comment by rmk135** [comment]
@kootoopas , I have updated the changelog and list of contributors https://github.com/ets-labs/python-dependency-injector/commit/9f6d2bb5221bb1c99d8898a930bbfb8f7758631f. Thanks for the fix and Happy New year!

**Comment by kootoopas** [comment]
@rmk135 You're welcome. I appreciate the feedback. Happy new year's!

**Pull request merged**
