### PR TITLE
Add Python 3.12 Support

### PR DESCRIPTION
**Pull request by anton-petrov**
# Description

Added support for **Python 3.12**

All tests passed ✌️

Ready for merge.

## Pinned dependencies:
- [x] cython==0.29.36
- [x] pydantic==1.10.13
- [x] flask==2.1.3
- [x] werkzeug==2.2.2
- [x] aiohttp==3.9.0b1

Fixed Github Actions for CI and tox configuration.
Removed tests for legacy python versions, supported only CPython >= 3.8 and PyPy >= 3.9

### CODE REVIEW

**Comment by batazor** [comment]
@boonya @ustims @rmk135 Please take a look when you have the opportunity

**Comment by abdullah-retorio** [comment]
Hello, 

I am planning to use your package in my new project. But i saw that you fixed the pydantic version in requirement-dev.txt. I need to use pydantic V2. Does this fix block my usage? If yes, will you support pydantic v2 and when?

**Comment by anton-petrov** [comment]
@abdullah-retorio Hi, pydantic version doesn't matter, it's only for tests. I successfully use pydanticV2 and this DI in my project.

**Comment by macieyng** [comment]
Hi 👋 
When can we expect this to be merged? 
https://github.com/aio-libs/aiohttp/issues/7639 seems to be resolved.
Linking issue #737.

**Comment by anton-petrov** [comment]
@rmk135 Hi, please, could you review?

**Comment by zeshuaro** [comment]
You might also want to update the CI config to also run tests on Python 3.12: https://github.com/ets-labs/python-dependency-injector/blob/master/.github/workflows/tests-and-linters.yml

**Comment by anton-petrov** [comment]
The reason why I deleted tests for an older python versions is - СPython version 3.7 and lower is no longer supported.

**Comment by rmk135** [comment]
@anton-petrov thanks a lot for the PR. For some reason, some of the tests are not passing. Also, I probably would keep Python 3.7 support for a little bit because it's still around 5% of users who haven't upgraded just yet.

I'm going to merge the PR as is into a feature branch and continue working on it there.

**Comment by mhassan5809** [comment]
hello @rmk135   when  this pr will get merge to main branch . 
Thanks .

**Comment by nerlijman** [comment]
Is there a new tag containing this ?

**Comment by fgreinacher** [comment]
@rmk135 Sorry for the ping, but it would be awesome if you could create a new release with this change. Also happy to help if some preparation work is needed. Just let me know 🙇

**Comment by macieyng** [comment]
@fgreinacher see #765

**Comment by rmk135** [comment]
The release with Python 3.12 support is on PyPI: https://pypi.org/project/dependency-injector/4.42.0b1/

```
pip install dependency-injector==4.42.0b1
```

Please report any issues you notice by opening an issue here: https://github.com/ets-labs/python-dependency-injector/issues

I'll publish the plan for future steps a bit later. There is a lot of work to do.

PS: [anton-petrov](https://github.com/anton-petrov) thank you for this PR again.

**Pull request merged**
